apiVersion: apps/v1
kind: Deployment
metadata:
  name: heh-flask
  labels:
    app: heh-flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heh-flask
  template:
    metadata:
      labels:
        app: heh-flask
    spec:
      containers:
        - name: heh-flask
<<<<<<< HEAD
          image: assiimm/heh-flask:b3fbbbf481717e95a6f0f547f5338bdf25a0cf50
          imagePullPolicy: IfNotPresent
=======
          image: assiimm/heh-flask:b3fbbbf481717e95a6f0f547f5338bdf25a0cf50
>>>>>>> bda9c7a78d5b6a6c2ff4ec52e37b92a03f74e50f
          ports:
            - containerPort: 5000
