apiVersion: apps/v1
kind: Deployment
metadata:
  name: heh-flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heh-flask
  template:
    metadata:
      labels:
        app: heh-flask
    spec:
      containers:
        - name: heh-flask
          image: assiimm/heh-flask:latest
          ports:
            - containerPort: 5000
